### ISSUE TITLE
Resize landing page

### ISSUE THREAD

**Issue by whysofast** [joaovictornsv/covidbr-tracker#1]
I don't know what's your screen resolution, but here, the landing page is a little bit off. It would be nice to resize your page by 5%, i don't know exactly so it fits better on every screen.
![image](https://user-images.githubusercontent.com/39545472/97086965-00d80b80-15fd-11eb-9e9d-0b14013d1d06.png)

**Comment by whysofast** [comment]
Setting height: 95vh; width: 95vw; was enough here

**Comment by joaovictornsv** [comment]
Hi Matheus, thanks for the alert. I made the dimensions correction.
